#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

source ~/.exports
source ~/.aliases
source ~/.path
source ~/.exports
if [ -f /usr/local/share/zsh/site-functions/_aws ] ; then
  source /usr/local/share/zsh/site-functions/_aws
fi


HISTFILE=~/.zsh_history
HISTSIZE=15000
SAVEHIST=15000
HISTORYCONTROL=ignorespace
unsetopt INC_APPEND_HISTORY
setopt APPEND_HISTORY
